### PR TITLE
[WIP]: docs(general): 📘 update documentation to reflect the new changes

### PR DESCRIPTION
**Pull request by luii**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/ngneat/query/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by luii** [comment]
@NetanelBasal A couple of questions: 
- The persisted query was relying on `keepPreviousData` now its relying on `placeholderData`, can i remove this example or should this be replaced? 
- You introduced `useMutationResult` for version `1.0` do we still need this example or wont this be in `2.0.0`?
- Should we keep the `Constructor DI` section or do you think this is not needed anymore with the introduction of the `inject*()` convention in this library?

**Comment by NetanelBasal** [comment]
- persisted query is removed
- useMutationResult is removed
- Constructor DI is removed

Docs should be:
query ( should show the fromPromise and the aborted signal you can optionally pass when you need to cancel the underline request)
infinite query
pagination
mutation
operators
config
is fetching/mutating
devtools
ssr
and showing signal where it supported

**Comment by NetanelBasal** [comment]
@luii I made more changes:
- intersectResults$ - Rx version
- intersectResults - Experimental signal support
- Create the query observer only upon subscription

https://github.com/ngneat/query/commit/2dce8e0b2e1d9703ded751db9becd8a35d68813c

**Comment by luii** [comment]
@NetanelBasal we maybe should revisit if `SSR` is still working?

**Comment by netanel-utila** [comment]
Yes

**Comment by netanel-utila** [comment]
I will take it from here. It will be great if you can take the playground and we can release on monday

**Comment by luii** [comment]
Okay, besides the styling, does the playground need a certain examples?

**Comment by netanel-utila** [comment]
Maybe a page that shows the operators and intersections functionality. That's all for now

**Pull request merged**
