### PR TITLE
issue(mutation): unsubscribe kill the usage of the mutation

### PR DESCRIPTION
**Pull request by ExFlo**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/ngneat/query/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

This is to show an issue I have after unsubscription on result$. The mutation is no longer working.

## What is the current behavior?

Issue Number: #82 

## Does this PR introduce a breaking change?

```
[ ] Yes
[ ] No
```

### CODE REVIEW

**Comment by NetanelBasal** [comment]
I'm not sure what the purpose of this PR

**Comment by ExFlo** [comment]
sorry @NetanelBasal this is only to showcase how to reproduce the issue  #82

**Comment by hichemfantar** [comment]
@ExFlo Please provide a reproduction using something like code sandbox or stackblitz.

**Comment by ExFlo** [comment]
I created a codesandbox instead [here](https://codesandbox.io/s/stupefied-lamport-0bj3z8?file=/src/app/app.component.ts)

**Pull request closed without merging**
