### PR TITLE
feat: adds angular 18 support

### LINKED ISSUE #179: support: angular v18
### Which @ngneat/query-* package(s) are relevant/releated to the feature request?

_No response_

### Description

Support to angular v18 would be beautiful

### Proposed solution

-

### Alternatives considered

-

### Do you want to create a pull request?

Yes

### PR DESCRIPTION
**Pull request by pavankjadda**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngneat/query/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

```
[x] Yes
[] No
```

## Other information
Closes #179

### CODE REVIEW

**Comment by pavankjadda** [comment]
Blocked by https://github.com/jscutlery/semver/issues/814

**Comment by rbalet** [comment]
@pavankjadda Hi, 

It seems they've fixed the error. 
Can you try it out ? 

https://github.com/bikecoders/ngx-deploy-npm/pull/606

**Comment by pavankjadda** [comment]
> @pavankjadda Hi,
> 
> It seems they've fixed the error. Can you try it out ?
> 
> [bikecoders/ngx-deploy-npm#606](https://github.com/bikecoders/ngx-deploy-npm/pull/606)

This https://github.com/jscutlery/semver/issues/814 blocks the PR

**Comment by dianjuar** [comment]
@rbalet, that was not a fix; was a workaround.

More info about the workaround:
https://github.com/jscutlery/semver/issues/814#issuecomment-2159702735

Here, you can find an implementation of that workaround
https://github.com/bikecoders/ngx-deploy-npm/pull/606/files#r1634121869

**Comment by driatvak** [comment]
Hi @pavankjadda ,
Any updates on when support to angular v18 will be out ? 🙏

**Comment by pavankjadda** [comment]
@NetanelBasal please merge this whenever you get a chance.

**Comment by NetanelBasal** [comment]
The commit should be marked a BREAKING CHANGE based on the convention

**Comment by pavankjadda** [comment]
> The commit should be marked a BREAKING CHANGE based on the convention

Done

**Comment by hakimio** [comment]
@NetanelBasal @pavankjadda the "breaking change" is not correct. The minimum Angular requirement in the `package.json` was not changed. It's still Angular 16.

**Comment by NetanelBasal** [comment]
@hakimio you're correct, my mistake. Never mind :)

**Comment by Drunkenpilot** [comment]
Got support error when install by npm  
```
npm i @ngneat/query-devtools
```

Error detail
```
npm ERR! Found: @angular/core@18.0.5
npm ERR! node_modules/@angular/core
npm ERR!   @angular/core@"^18.0.5" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/core@">=16.0.0 <18.0.0" from @ngneat/query-devtools@2.0.0-beta.0
npm ERR! node_modules/@ngneat/query-devtools
npm ERR!   dev @ngneat/query-devtools@"*" from the root project
```

**Comment by pavankjadda** [comment]
@NetanelBasal could you release 3.0.0 version for dev tools as well?

**Comment by pavankjadda** [comment]
> Got support error when install by npm
> 
> ```
> npm i @ngneat/query-devtools
> ```
> 
> Error detail
> 
> ```
> npm ERR! Found: @angular/core@18.0.5
> npm ERR! node_modules/@angular/core
> npm ERR!   @angular/core@"^18.0.5" from the root project
> npm ERR! 
> npm ERR! Could not resolve dependency:
> npm ERR! peer @angular/core@">=16.0.0 <18.0.0" from @ngneat/query-devtools@2.0.0-beta.0
> npm ERR! node_modules/@ngneat/query-devtools
> npm ERR!   dev @ngneat/query-devtools@"*" from the root project
> ```

For now use `npm i @ngneat/query-devtools --legacy-peer-deps`

**Comment by NetanelBasal** [comment]
We first need to update the peer

**Comment by pavankjadda** [comment]
> We first need to update the peer

it was already updated in last PR https://github.com/ngneat/query/blob/main/devtools/package.json#L13

**Pull request merged**
